defaults:
  cluster: ${CLUSTER}
  environment:
    name: '"sfdemo-" ~ code_reference.branch'

variables:
  - name: SYMFONY_ENV
    value: prod

tasks:
  images:
    build:
      services:
        web:
          image: ${IMAGE_NAME}
          naming_strategy: sha1
  deployment:
    deploy:
      services:
        web:
          endpoints:
            -
              name: webtest
              ingress:
                class: nginx
                host:
                  expression: '"sfdemo.inviqa-rmiller.continuouspipe.net"'
          specification:
            environment_variables:
              - name: SYMFONY_ENV
                value: ${SYMFONY_ENV}


pipelines:
  - name: Production
    condition: 'not(code_reference.branch matches "/^cpdev/")'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "/^cpdev/"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: dev


