defaults:
  cluster: ${CLUSTER}
  environment:
    name: '"sfdemo-" ~ code_reference.branch'

variables:
  - name: SYMFONY_ENV
    value: prod

pipelines:
  - name: Production
    condition: 'code_reference.branch in ["master"]'
    tasks: [ images, deployment ]
  - name: Feature branches
    condition: 'code_reference.branch not in ["master"] and not(code_reference.branch matches "#^cpdev/#")'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "#^cpdev/#"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: dev

tasks:
  images:
    build:
      services:
        web:
          image: ${IMAGE_NAME}
          naming_strategy: sha1

  deployment:
    deploy:
      services:
        web:
          endpoints:
            -
                name: http
                type: internal
                httplabs:
                    api_key: ${HTTPLABS_API_KEY}
                    project_identifier: ${HTTPLABS_PROJECT_ID}
                    record_suffix: "-sfdemo.httplabs.net"
                    middlewares:
                        - name: backend-ssl
                          config:
                            type: any
                        - name: https-only
                        - name: auth0
                          config:
                               client-id: ${AUTH0_CLIENT_ID}
                               client-secret: ${AUTH0_CLIENT_SECRET}
                               domain: ${AUTH0_DOMAIN}
                               authorized-email-domain: inviqa.com
                               cookie-https: false
                               public-key: ${AUTH0_PUBLIC_KEY}
          specification:
            environment_variables:
              - name: SYMFONY_ENV
                value: ${SYMFONY_ENV}
pipelines:
  - name: Production
    condition: 'not(code_reference.branch matches "/^cpdev/")'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "/^cpdev/"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: dev

