defaults:
  cluster: ${CLUSTER}
  environment:
    name: '"sfdemo-" ~ code_reference.branch'

variables:
  - name: SYMFONY_ENV
    value: prod

tasks:
  images:
    build:
      services:
        web:
          image: ${IMAGE_NAME}
          naming_strategy: sha1
  deployment:
    deploy:
      services:
        web:
          endpoints:
            -
                name: http
                httplabs:
                    api_key: ${HTTPLABS_API_KEY}
                    project_identifier: ${HTTPLABS_PROJECT_ID}
                    middlewares:
                        - template: https://api.httplabs.io/projects/${HTTPLABS_PROJECT_ID}/templates/backend-ssl
                          config:
                            type: any
                        - template: https://api.httplabs.io/projects/${HTTPLABS_PROJECT_ID}/templates/https-only
                        - template: https://api.httplabs.io/projects/${HTTPLABS_PROJECT_ID}/templates/auth0
                          config:
                               client-id: ${AUTH0_CLIENT_ID}
                               client-secret: ${AUTH0_CLIENT_SECRET}
                               callback-url: ${AUTH0_CALLBACK_URL}
                               domain: ${AUTH0_DOMAIN}
                               authorized-email-domain: inviqa.com
                               cookie-domain: ${AUTH0_COOKIE_DOMAIN}
                               cookie-https: false
                               public-key: ${AUTH0_PUBLIC_KEY}
          specification:
            environment_variables:
              - name: SYMFONY_ENV
                value: ${SYMFONY_ENV}


pipelines:
  - name: Production
    condition: 'not(code_reference.branch matches "/^cpdev/")'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "/^cpdev/"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: dev


