defaults:
  cluster: ${CLUSTER}
  environment:
    name: '"sfdemo-" ~ code_reference.branch'

variables:
  - name: SYMFONY_ENV
    value: prod

tasks:
  images:
    build:
      services:
        web:
          image: ${IMAGE_NAME}
          naming_strategy: sha1
  deployment:
    deploy:
      services:
        web:
          endpoints:
            -
                name: http
                httplabs:
                    api_key: ${HTTPLABS_API_KEY}
                    project_identifier: ${HTTPLABS_PROJECT_ID}
                    middlewares:
                        - template: https://api.httplabs.io/projects/${HTTPLABS_PROJECT_ID}/templates/basic-auth
                          config:
                              realm: This is secure!
                              username: ${BASIC_AUTH_USERNAME}
                              password: ${BASIC_AUTH_PASSWORD}
          specification:
            accessibility:
              from_external: true
            environment_variables:
              - name: SYMFONY_ENV
                value: ${SYMFONY_ENV}


pipelines:
  - name: Production
    condition: 'not(code_reference.branch matches "/^cpdev/")'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "/^cpdev/"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: dev


