defaults:
  cluster: ${CLUSTER}
  environment:
    name: '"sfdemo-" ~ code_reference.branch'

variables:
  - name: SYMFONY_ENV
    value: prod

tasks:
  images:
    build:
      services:
        web:
          image: ${IMAGE_NAME}
          naming_strategy: sha1
  deployment:
    deploy:
      services:
        web:
          endpoints:
            -
              name: webtest
              cloud_flare_zone:
                zone_identifier: ${CLOUD_FLARE_ZONE}
                authentication:
                    email: ${CLOUD_FLARE_EMAIL}
                    api_key: ${CLOUD_FLARE_API_KEY}
                proxied: true
                record_suffix: '-rm-inviqa.continuouspipe.net'
              ingress:
                class: nginx
                host_suffix: '-rm-inviqa.continuouspipe.net'
          specification:
            environment_variables:
              - name: SYMFONY_ENV
                value: ${SYMFONY_ENV}


pipelines:
  - name: Production
    condition: 'not(code_reference.branch matches "/^cpdev/")'
    tasks: [ images, deployment ]
  - name: Remote
    condition: 'code_reference.branch matches "/^cpdev/"'
    tasks: [ images, deployment ]
    variables:
      - name: SYMFONY_ENV
        value: dev


