version: "2"

services:
  web:
    build:
      context: .
    expose:
      - 80
      - 443
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/app
    environment:
      WEB_HTTPS_ONLY: "true"
